#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Prüfen, ob das Skript als root läuft
if [[ "$EUID" -ne 0 ]]; then
  echo "Bitte als root ausführen."
  exit 1
fi

echo "=== Debian Setup Startup-Script ==="

# 1) Hostname ändern
read -rp "Neuen Hostname eingeben (z.B. mein-server): " NEW_HOSTNAME
echo "Hostname wird zu '$NEW_HOSTNAME' geändert..."
# Backup
cp /etc/hostname /etc/hostname.bak
cp /etc/hosts    /etc/hosts.bak
# setzen
echo "$NEW_HOSTNAME" > /etc/hostname
hostnamectl set-hostname "$NEW_HOSTNAME"
# /etc/hosts anpassen (127.0.1.1)
sed -i "s/^\(127\.0\.1\.1\s*\).*$/\1$NEW_HOSTNAME/" /etc/hosts
echo "Hostname angepasst."

# 2) Netzwerk-Konfiguration ändern
echo
read -rp "Netzwerk-Interface (z.B. eth0 oder ens3): " IFACE
read -rp "Statische IPv4-Adresse (z.B. 192.168.1.100): " IP_ADDR
read -rp "Netzmaske (z.B. 255.255.255.0): " NETMASK
read -rp "Gateway (z.B. 192.168.1.1): " GATEWAY
read -rp "DNS-Server (z.B. 8.8.8.8 8.8.4.4): " DNS_SERVERS

echo "Backup der bisherigen /etc/network/interfaces nach /etc/network/interfaces.bak"
cp /etc/network/interfaces /etc/network/interfaces.bak

cat > /etc/network/interfaces <<EOF
# This file was autogenerated by startup.sh on $(date)
auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet static
    address $IP_ADDR
    netmask $NETMASK
    gateway $GATEWAY
    dns-nameservers $DNS_SERVERS
EOF

echo "Netzwerk-Config geschrieben. Wende an..."
# Schnittstelle neu starten
ifdown "$IFACE" 2>/dev/null || true
ifup   "$IFACE"
echo "Netzwerk neu gestartet."

# 3) System aktualisieren
echo
echo "Starte System-Update..."
apt update
apt -y upgrade
apt -y dist-upgrade
# Optional: auf das Meta-Paket für den neuesten Kernel zünden
apt -y install linux-image-amd64
# Nicht mehr benötigte Pakete entfernen
apt -y autoremove
echo "Update abgeschlossen."

EOF

# Neustart
read -rp "Alles fertig – Server jetzt neu starten? [j/N] " REBOOT
case "$REBOOT" in
  [jJ]|[jJ][aA]|[yY] )
    echo "Neustart wird durchgeführt..."
    reboot
    ;;
  * )
    echo "Skript beendet. Bitte später manuell neustarten."
    ;;
esac

exit 0
